const seedAreas = <String>[
  'health',
  'learning',
  'career',
  'relationships',
  'projects',
  'self_improvement',
  'finance',
];

const areaLabels = <String, String>{
  'health': 'Health',
  'learning': 'Learning',
  'career': 'Career',
  'relationships': 'Relationships',
  'projects': 'Projects',
  'self_improvement': 'Self Improvement',
  'finance': 'Finance',
};

const seedHabitNames = <String, double>{
  'Morning workout': 0.72,
  'Read 20 pages': 0.65,
  'Meditate 10 min': 0.80,
  'Drink 2L water': 0.85,
  'Study NEET material': 0.55,
  'Journal evening': 0.60,
  'Call family': 0.40,
  'Work on project': 0.50,
  'Plan tomorrow': 0.70,
  'Screens off by 11pm': 0.50,
};

const seedEntryTemplates = <String>[
  'Worked on {topic} today. Progress was {adverb}, but consistent.',
  'Had a {adj} day. Main win: {win}. Tomorrow: {next}.',
  'Studied {topic} for {hours} hours. Focus was {focus}.',
  'Training day. {exercise} felt {feeling}. Body is {body_state}.',
  'Quiet day. Spent time on {topic} and on rest. Notes: {note}.',
  'Met with {person}. Talked about {topic}. Good {outcome}.',
  'Energy {level} today. What helped: {help}. What hurt: {hurt}.',
  'Journal check-in. Current goal: {goal}. Honest status: {status}.',
  'Documented {topic}. It matters because {why}.',
  'Slow morning, strong evening. Finished {win}.',
  'Reflecting on this week: {week_note}. Adjustment: {next}.',
  'Pushed through {hardship} today. It was worth it.',
  'Built {thing} for the project. Next step: {next}.',
  'Noticed pattern: {pattern}. Plan: {plan}.',
  'Grateful for {gratitude}. Learned: {lesson}.',
  'Deep work on {topic}. Distractions: {distraction}.',
  'Body check: {body_state}. Recovery needed: {recovery}.',
  'Read about {topic}. Key takeaway: {takeaway}.',
  'Phone time was {screen_time}. Tomorrow: {next}.',
  'End of day. Today was {overall}.',
];

const seedTags = <String>[
  'focus',
  'low-day',
  'win',
  'streak',
  'rest',
  'gym',
  'study',
  'family',
  'project',
  'energy',
  'discipline',
  'reflection',
];

const seedFillers = <String, List<String>>{
  'topic': ['coding', 'math', 'physics', 'english', 'fitness plan', 'the book', 'portfolio', 'habits'],
  'adverb': ['slowly', 'steadily', 'well', 'inconsistently', 'surprisingly well'],
  'adj': ['long', 'full', 'hard', 'calm', 'productive', 'messy'],
  'win': ['the workout', 'deep focus block', 'family call', 'chapter read', 'project milestone', 'early start'],
  'next': ['start earlier', 'finish the chapter', 'one more rep set', 'prep meals', 'plan the week'],
  'hours': ['2', '3', '1.5', '4', '2.5'],
  'focus': ['high', 'medium', 'low', 'scattered', 'sharp after coffee'],
  'exercise': ['squats', 'bench', 'deadlifts', 'pull-ups', 'run', 'abs work'],
  'feeling': ['strong', 'heavy but good', 'lighter', 'mechanical', 'energized'],
  'body_state': ['recovering well', 'sore but fine', 'tired', 'leaner', 'needs more sleep'],
  'person': ['a friend', 'family', 'a colleague', 'an old classmate'],
  'outcome': ['conversation', 'plan', 'catch-up', 'decision'],
  'level': ['high', 'moderate', 'low'],
  'help': ['early sleep', 'music', 'sunlight', 'a walk', 'planning'],
  'hurt': ['phone scrolling', 'late night', 'skipped breakfast', 'noise'],
  'goal': ['the current one', 'the habit streak', 'the project', 'the study plan'],
  'status': ['on track', 'slipping', 'ahead', 'starting over', 'consistent'],
  'why': ['it compounds', 'future me needs it', 'it is the plan', 'discipline'],
  'week_note': ['busy', 'solid', 'uneven', 'surprisingly good'],
  'hardship': ['tiredness', 'motivation dip', 'a long commute', 'distractions'],
  'thing': ['a small tool', 'the routine', 'a draft', 'the plan'],
  'pattern': ['late nights kill mornings', 'good after gym', 'cravings at 10pm'],
  'plan': ['move sleep earlier', 'protect the workout', 'snack smarter'],
  'gratitude': ['health', 'the streak', 'quiet time', 'support', 'small wins'],
  'lesson': ['consistency beats intensity', 'rest is part of training', 'start ugly'],
  'distraction': ['low today', 'social media', 'noise', 'erratic schedule'],
  'recovery': ['an earlier night', 'a lighter session', 'a walk'],
  'takeaway': ['do it badly first', 'compound interest', 'show up daily'],
  'screen_time': ['bad', 'okay', 'better than yesterday', 'high'],
  'overall': ['a win', 'a draw', 'fine', 'hard but good', 'quiet'],
};
